#ifndef CONSTANTS_GLSL
#define CONSTANTS_GLSL

const uint BINDING_POINT_CAMERA_SSBO = 0;
const uint BINDING_POINT_ENVIRONMENT_LIGHT_SSBO = 1;
const uint BINDING_POINT_POINTLIGHT_SSBO = 2;
const uint BINDING_POINT_SPOTLIGHT_SSBO = 3;
const uint BINDING_POINT_MATERIAL_SSBO = 4;
const uint BINDING_POINT_MODEL_SSBO = 5;
const uint BINDING_POINT_ENTITY_SSBO = 6;
const uint BINDING_POINT_PROCESSING_SSBO = 7;

#endif
