#ifndef CONSTANTS_GLSL
#define CONSTANTS_GLSL


const uint CAMERA_SSBO_BINDING_POINT = 0;
const uint ENVIRONMENT_LIGHT_SSBO_BINDING_POINT = 1;
const uint POINTLIGHT_SSBO_BINDING_POINT = 2;
const uint SPOTLIGHT_SSBO_BINDING_POINT = 3;


#endif